### ISSUE TITLE
Token解密

### ISSUE THREAD

**Issue by ghost** [EalenXie/shiro-jwt-applet#1]
/**
     * 根据Token 获取wxOpenId(注意坑点 : 就算token不正确，也有可能解密出wxOpenId,同下)
     */
    public String getWxOpenIdByToken(String token) throws JWTDecodeException {
        return JWT.decode(token).getClaim("wxOpenId").asString();
    }

看到您的注释，请问token不正确也能解密出来?这个应该怎么处理？

**Comment by EalenXie** [comment]
目前token不正确，解密出来相关信息，因为这是JWT的内部实现，我这边也没有比较好的处理方法。
但是 wxOpenId，sessionKey，jwt-id三个参数一起签名得到的token，如果传递的token不正确，则三个参数可能会有一两个参数会被解密出来，但不可能三个参数都被解密出来，JWTVerifier也不可能验证通过。
所以就算token不正确解密出来相关信息，也是能保证验证是安全的。

**Comment by ghost** [comment]
JwtConfig 中的 verifyToken 方法：

`verifier.verify(redisToken);
`

这一行为什么不是传入 token ，而是 redisToken 呢。
